version: "3.7"

services:
  web-app:
    build:
      context: ./
      dockerfile: ./docker/web-app.docker
    container_name: web-app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/